In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]
arr=np.array(lst)

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.shape

(5,)

In [8]:
type(arr)

numpy.ndarray

In [ ]:
2D-Array

In [10]:
list1=[1,2,3,4,5]
list2=[3,4,5,6,7]
list3=[5,6,7,8,9]
arr1=np.array([list1,list2,list3])


In [11]:
arr1


array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [14]:
arr1.shape

(3, 5)

In [15]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 6],
       [7, 5, 6],
       [7, 8, 9]])

In [16]:
arr2=np.array([1,2,3,4,5,6,7,8,9])

In [17]:
arr2.shape

(9,)

In [18]:
arr2.reshape(1,9)


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
arr2[4]

5

In [ ]:
Accessing the values of arr1 from indexing in 2d arrays

In [22]:
arr1[:,:]

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [23]:
arr1[1:,2:]

array([[5, 6, 7],
       [7, 8, 9]])

In [24]:
arr1[:1,:2]

array([[1, 2]])

In [27]:
arr1[:3,:3]

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [30]:
arr1[0:2,0:2]   #lower bound and upper bounds play an imp role , say [1:3] , it basically means - rows 1,2 and not 3rd row

array([[1, 2],
       [3, 4]])

In [31]:
arr1[0,2]

3

In [32]:
arr1[0,:4]

array([1, 2, 3, 4])

In [33]:
arr3=np.array([1,2,3,4,5,2,3,4,5,6,9,7,6,8,9])

In [34]:
arr3.shape

(15,)

In [35]:
arr3.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [41]:
arr3

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9])

In [42]:
arr4=arr3.reshape(3,5)

In [43]:
arr4

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [45]:
arr4[1:,2:4]


array([[4, 5],
       [6, 8]])

In [46]:
arr4[1:2,1:4]

array([[3, 4, 5]])

In [49]:
arr4


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [55]:
#copy function
arr4[3:]=100            #after 3rd index , convert every values to 100


In [56]:
arr4                #OOPS , the array got changed completely , so to minimize the retundency and create a healthy memory eccosystem .. we use copy function

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [57]:
arr5=arr4.copy()

In [58]:
arr5          #arr5 has elements copied from arr4

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [59]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#some conditions are very helpful in learning and implementing Data analytics

In [63]:
val=2
arr5[arr5<=val]
arr<2

array([ True, False, False, False, False])

##

In [66]:
arr5%10


array([0, 1, 2, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [67]:
arr5%2


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [68]:
np.ones(4)

array([1., 1., 1., 1.])

In [77]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 9, 16, 25, 36, 49],
       [25, 36, 49, 64, 81]])

In [70]:
arr4*arr5

array([    0,     1,     4, 10000, 10000, 10000, 10000, 10000, 10000,
       10000])

In [73]:
np.ones((2,5),dtype=int)           #initialized the values of ones to be int 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [75]:
arr_ex=np.random.rand(3,3)
arr_ex

array([[0.81153546, 0.80784696, 0.8576514 ],
       [0.54117937, 0.99243176, 0.1363316 ],
       [0.39588684, 0.01122239, 0.29510233]])

In [76]:
np.random.random_sample((3,10))

array([[0.11193131, 0.22945658, 0.43508464, 0.4608124 , 0.39018473,
        0.3975685 , 0.09325252, 0.28605911, 0.93335756, 0.17345794],
       [0.58266373, 0.01119169, 0.87284044, 0.21517129, 0.22112694,
        0.02586692, 0.77833232, 0.48336621, 0.09292505, 0.59512271],
       [0.8171791 , 0.38712358, 0.05733193, 0.29030228, 0.23859325,
        0.68835445, 0.67003694, 0.69212666, 0.56037991, 0.20802994]])